services:
  backend:
    build: 
      context: ./backend
      args:
        - UID=1000
        - GID=1000
    container_name: horta-backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    tty: true