services:
  backend:
    build: 
      context: ./backend
      args:
        - UID=1000
        - GID=1000
    container_name: horta-backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: horta-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  db_data:
